# Generated by Django 5.0.6 on 2024-09-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
